name: brml
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.2
  - matplotlib=3.3.4
  - pymc3=3.10.0
  - scipy=1.6.2
  - numpy=1.20.1
  - scikit-learn=0.24.1
  - statsmodels=0.12.2
  - theano=1.0.5
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pytest=6.2.2
  - pytest-mock=3.5.1
  - pre_commit=2.10.1
  - autopep8=1.5.5
  - line_profiler=2.1.2
  - memory_profiler=0.58.0
  - pytest-benchmark=3.4.1
  - numba=0.53.1
  - dask=2021.6.0
  - distributed=2021.6.0
  - jupyter-server-proxy=3.0.2
  - tornado=6.1.0
  - pytest-tornasync=0.6.0.post1
  - python-graphviz=0.16

